# Generated by Django 6.0.5 on 2026-05-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='calculated_distance',
            field=models.IntegerField(default=0, help_text='Distance in kilometers'),
        ),
        migrations.AddField(
            model_name='booking',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimated price in USD', max_digits=10),
        ),
    ]
