# Generated by Django 6.0.5 on 2026-05-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_booking_calculated_distance_booking_estimated_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('UGX', 'UGX')], default='USD', max_length=3),
        ),
    ]
