# Generated by Django 6.0.5 on 2026-05-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_booking_status_booking_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delivery_code',
            field=models.CharField(blank=True, help_text='Code for customer to verify delivery', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_verified',
            field=models.BooleanField(default=False),
        ),
    ]
