# Generated by Django 4.2.30 on 2026-05-17 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_booking_status_booking_tracking_number'),
        ('logistics', '0005_booking_delivery_code_booking_delivery_verified'),
    ]

    operations = [
    ]
