services:
  - type: web
    name: fleeting
    buildCommand: |
      python -m pip install -r requirements.txt
      python manage.py migrate --no-input
      python manage.py collectstatic --no-input
      python manage.py create_superuser
    startCommand: gunicorn logistics_project.wsgi:application --bind 0.0.0.0:$PORT --log-level info
    envVars:
      - key: DATABASE_URL
        value: "postgresql://fleeting_database_user:A5aaaCtGAXNhjmYbPzRTUKP8gZBE4Nn1@dpg-d8o37lhkh4rs73eaf8t0-a/fleeting_database"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "fleeting-g9x8.onrender.com"
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false