services:
  - type: web
    name: fleeting
    buildCommand: |
      python -m pip install -r requirements.txt
      python manage.py migrate --no-input
      python manage.py collectstatic --no-input || true
      python manage.py createsuperuser --no-input --username=admin --email=admin@fleeting.com || true
    startCommand: gunicorn logistics_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "fleeting.onrender.com"
    # Point to the PostgreSQL database
    database:
      name: fleeting