# Generated by Django 6.0.6 on 2026-06-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='capacity',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='capacity_passengers',
            field=models.CharField(blank=True, choices=[('5', '5 Passengers'), ('7', '7 Passengers'), ('12', '12 Passengers'), ('14', '14 Passengers'), ('18', '18 Passengers'), ('25', '25 Passengers'), ('30', '30 Passengers'), ('35', '35 Passengers'), ('40', '40 Passengers'), ('50', '50 Passengers'), ('60', '60 Passengers')], help_text='Passenger capacity', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='capacity_tonnes',
            field=models.CharField(blank=True, choices=[('1', '1 Ton'), ('2', '2 Tons'), ('3', '3 Tons'), ('5', '5 Tons'), ('7', '7 Tons'), ('10', '10 Tons'), ('15', '15 Tons'), ('20', '20 Tons'), ('25', '25 Tons'), ('30', '30 Tons')], help_text='Cargo capacity in tonnes', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='diesel', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Isuzu', 'Isuzu'), ('Ford', 'Ford'), ('Nissan', 'Nissan'), ('Mitsubishi', 'Mitsubishi'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia'), ('Yutong', 'Yutong'), ('King Long', 'King Long'), ('Hino', 'Hino'), ('DAF', 'DAF'), ('Volvo', 'Volvo'), ('Scania', 'Scania'), ('MAN', 'MAN')], help_text='Vehicle make/manufacturer', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(choices=[(2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026')], help_text='Manufacturing year'),
        ),
    ]
