# Generated by Django 6.0.6 on 2026-06-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_update_vehicle_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='mileage_interval',
            field=models.IntegerField(default=5000, help_text='Service interval in km'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='next_service_due',
            field=models.DateField(blank=True, help_text='Next scheduled service date', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='service_interval_days',
            field=models.IntegerField(default=90, help_text='Service interval in days'),
        ),
    ]
