# Generated by Django 6.0.6 on 2026-06-16 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_add_maintenance_tracking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Trips'},
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.IntegerField(default=0, help_text='Distance in km'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='fleet.driver'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='fleet.vehicle'),
        ),
    ]
